### ISSUE TITLE
pub.lua fail to compile with bcc 0.80

### ISSUE THREAD

**Issue by olejr** [bmx-ng/bcc#222]
Don't know if bcc is to blame, or pub.lua.
But after upgrading bcc to latest from git I get the following error when (trying to) build modules:
```
BlitzMax/mod/pub.mod/lua.mod/.bmx/lua.bmx.debug.win32.x86.c:109:2: error: 'BBDEBUGSCOPE_USERSTRUCT' undeclared here (not in a function)
  BBDEBUGSCOPE_USERSTRUCT,
  ^
```
Windows 10, gcc version 5.1.0 (tdm64-1)
Working bcc used until now: v0.79 built on 23 may.

**Comment by woollybah** [comment]
Are your (brl/pub) modules up-to-date?

**Comment by olejr** [comment]
Yes, did a 'git pull' on everything under bmx-ng.
And no. Seem late hours made me do stupid things.
Forgot to actually copy the new pub.mod folder to my BlitzMax folder..

Now after removing all mods in the mod folder, and a fresh copy of just brl & pub mod things work.
(Reason for removing mods you can see under my issue with bmk)
