### ISSUE TITLE
Module compilation has trouble with "Command.."

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#136]
When trying to recompile modules I came across this error:

`Compile Error: Expecting expression but encountered '*'`
The highlighted line is in __mod/brl.mod/max2d.mod/max2d.bmx__
```BlitzMax
	_max2dDriver.Plot..
	px*gc.tform_ix+py*gc.tform_iy+x+gc.origin_x,px*gc.tform_jx+py*gc.tform_jy+y+gc.origin_y
```
The same error happened in mky.mod (mojo2) - so I replaced the 2 lines with a oneliner - and this line was error free.

So up to the next one: `Compile Error: Missing function argument 'x0'.`
Same module - same file.
```BlitzMax
Function DrawRect( x#,y#,width#,height# )
	_max2dDriver.DrawRect..
	gc.handle_x,gc.handle_y,..
	gc.handle_x+width,gc.handle_y+height,..
	x+gc.origin_x,y+gc.origin_y
End Function
```

Seems BCC eats something it shouldn't.

Edit: wrapping it in brackets ... resolves the issue (`_max2dDriver.DrawRect(..` ... `x+gc.origin_x,y+gc.origin_y)`)

**Comment by woollybah** [comment]
This is working fine for me... :hamster:

**Comment by GWRon** [comment]
Are you sure?

- fetched latest BCC-sources
- opened up MaxIDE and clicked "rebuild all modules"

```
ar: creating /PATH_TO/BlitzMaxNG/mod/brl.mod/glgraphics.mod/glgraphics.debug.linux.x86.a
[ 97%] Compiling:imagefont.bmx.debug.linux.x86.c
[ 97%] Compiling:mojo2.bmx.debug.linux.x86.c
[ 98%] Archiving:glsdlgraphics.debug.linux.x86.a
ar: creating /PATH_TO/BlitzMaxNG/mod/sdl.mod/glsdlgraphics.mod/glsdlgraphics.debug.linux.x86.a
[ 98%] Processing:max2d.bmx
[ 98%] Archiving:mojo2.debug.linux.x86.a
ar: creating /PATH_TO/BlitzMaxNG/mod/mky.mod/mojo2.mod/mojo2.debug.linux.x86.a
Compile Error: Expecting expression but encountered '*'
[/PATH_TO/BlitzMaxNG/mod/brl.mod/max2d.mod/max2d.bmx;304;0]
Build Error: failed to compile (65280) /PATH_TO/BlitzMaxNG/mod/brl.mod/max2d.mod/max2d.bmx
Process complete
```

bye
Ron

**Comment by Dabzy** [comment]
Getting this as well...

[ 97%] Processing:max2d.bmx
Compile Error: Expecting expression but encountered '*'
[C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448828615/BlitzMaxNG/mod/brl.mod/max2d.mod/max2d.bmx;304;0]
Build Error: failed to compile C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448828615/BlitzMaxNG/mod/brl.mod/max2d.mod/max2d.bmx
Process complete

Dabz

**Comment by GWRon** [comment]
Error was introduced with commit 825345f3cb712ff56e095b025973ee36d500ed6b ("Don't push line continuation symbol to parser").

**Comment by GWRon** [comment]
Maybe we should consider adding an additional variable "currentLine" next to "start", so we could adjust them separately.
So regarding the "wrong line reported"-issue you then return the "currentLine" variable while the "logic" is using "start" to parse and validate content.

**Comment by woollybah** [comment]
Fun fun...  may be fixed now.
Took me a while to find a version that replicated the error. Unsure why it was working here.
It seems that stripping dotdot during preprocessing was causing the main issue when tokenizing proper...

**Comment by Dabzy** [comment]
It got passed the error above, but now I'm getting:-

[ 99%] Compiling:untitled1.bmx.gui.debug.win32.x86.c
[100%] Linking:untitled1.debug.exe
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/max2d.mod/max2d.debug.win32.x86.a(max2d.bmx.debug.win32.x86.o): In function `_bb_brl_max2d_max2d':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/max2d.mod/.bmx/max2d.bmx.debug.win32.x86.c:7463: undefined reference to `_bb_____brl_max2d_image'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/max2d.mod/.bmx/max2d.bmx.debug.win32.x86.c:7464: undefined reference to `_bb_____brl_max2d_imagefont'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/max2d.mod/max2d.debug.win32.x86.a(image.bmx.debug.win32.x86.o): In function `bb_brl_max2d_image':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/max2d.mod/.bmx/image.bmx.debug.win32.x86.c:847: undefined reference to `_bb_____brl_max2d_driver'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/max2d.mod/max2d.debug.win32.x86.a(imagefont.bmx.debug.win32.x86.o): In function `bb_brl_max2d_imagefont':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/max2d.mod/.bmx/imagefont.bmx.debug.win32.x86.c:1141: undefined reference to `_bb_____brl_max2d_image'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/glgraphics.mod/glgraphics.debug.win32.x86.a(glgraphics.bmx.debug.win32.x86.o): In function `_bb_brl_glgraphics_glgraphics':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/glgraphics.mod/.bmx/glgraphics.bmx.debug.win32.x86.c:7: undefined reference to `_bb_____brl_glgraphics_source'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/dxgraphics.mod/dxgraphics.debug.win32.x86.a(dxgraphics.bmx.debug.win32.x86.o): In function `_bb_brl_dxgraphics_dxgraphics':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/dxgraphics.mod/.bmx/dxgraphics.bmx.debug.win32.x86.c:7: undefined reference to `_bb_____brl_dxgraphics_d3d9graphics'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/systemdefault.mod/systemdefault.debug.win32.x86.a(systemdefault.bmx.debug.win32.x86.o): In function `_bb_brl_systemdefault_systemdefault':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/systemdefault.mod/.bmx/systemdefault.bmx.debug.win32.x86.c:8: undefined reference to `_bb_____brl_systemdefault_system_win32'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/system.mod/system.debug.win32.x86.a(system.bmx.debug.win32.x86.o): In function `_bb_brl_system_system':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/system.mod/.bmx/system.bmx.debug.win32.x86.c:586: undefined reference to `_bb_____brl_system_driver'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/directx.mod/directx.debug.win32.x86.a(directx.bmx.debug.win32.x86.o): In function `_bb_pub_directx_directx':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/directx.mod/.bmx/directx.bmx.debug.win32.x86.c:7: undefined reference to `_bb_____pub_directx_dd'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/directx.mod/.bmx/directx.bmx.debug.win32.x86.c:8: undefined reference to `_bb_____pub_directx_d3d'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/directx.mod/.bmx/directx.bmx.debug.win32.x86.c:9: undefined reference to `_bb_____pub_directx_d3d7'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/directx.mod/.bmx/directx.bmx.debug.win32.x86.c:10: undefined reference to `_bb_____pub_directx_d3d9'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/directx.mod/.bmx/directx.bmx.debug.win32.x86.c:11: undefined reference to `_bb_____pub_directx_d3d9x'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/directx.mod/.bmx/directx.bmx.debug.win32.x86.c:12: undefined reference to `_bb_____pub_directx_dsound'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/directx.mod/directx.debug.win32.x86.a(d3d9.bmx.debug.win32.x86.o): In function `bb_pub_directx_d3d9':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/directx.mod/.bmx/d3d9.bmx.debug.win32.x86.c:6980: undefined reference to `_bb_____pub_directx_d3d'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/pixmap.mod/pixmap.debug.win32.x86.a(pixmap.bmx.debug.win32.x86.o): In function `_bb_brl_pixmap_pixmap':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/pixmap.mod/.bmx/pixmap.bmx.debug.win32.x86.c:2411: undefined reference to `_bb_____brl_pixmap_pixel'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/audiosample.mod/audiosample.debug.win32.x86.a(audiosample.bmx.debug.win32.x86.o): In function `_bb_brl_audiosample_audiosample':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/audiosample.mod/.bmx/audiosample.bmx.debug.win32.x86.c:716: undefined reference to `_bb_____brl_audiosample_sample'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/freetype.mod/freetype.debug.win32.x86.a(freetype.bmx.debug.win32.x86.o): In function `_bb_pub_freetype_freetype':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/freetype.mod/.bmx/freetype.bmx.debug.win32.x86.c:642: undefined reference to `_bb_____pub_freetype_source'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/win32.mod/win32.debug.win32.x86.a(win32.bmx.debug.win32.x86.o): In function `_bb_pub_win32_win32':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/win32.mod/.bmx/win32.bmx.debug.win32.x86.c:7: undefined reference to `_bb_____pub_win32_gdi32'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/win32.mod/.bmx/win32.bmx.debug.win32.x86.c:8: undefined reference to `_bb_____pub_win32_user32'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/win32.mod/.bmx/win32.bmx.debug.win32.x86.c:9: undefined reference to `_bb_____pub_win32_kernel32'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/win32.mod/.bmx/win32.bmx.debug.win32.x86.c:10: undefined reference to `_bb_____pub_win32_winmm'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/win32.mod/.bmx/win32.bmx.debug.win32.x86.c:11: undefined reference to `_bb_____pub_win32_com'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/win32.mod/.bmx/win32.bmx.debug.win32.x86.c:12: undefined reference to `_bb_____pub_win32_commdlg'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/win32.mod/.bmx/win32.bmx.debug.win32.x86.c:13: undefined reference to `_bb_____pub_win32_commctrl'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/win32.mod/.bmx/win32.bmx.debug.win32.x86.c:14: undefined reference to `_bb_____pub_win32_richedit'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/opengl.mod/opengl.debug.win32.x86.a(opengl.bmx.debug.win32.x86.o): In function `_bb_pub_opengl_opengl':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/pub.mod/opengl.mod/.bmx/opengl.bmx.debug.win32.x86.c:7: undefined reference to `_bb_____pub_opengl_glu'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/map.mod/map.debug.win32.x86.a(map.bmx.debug.win32.x86.o): In function `_bb_brl_map_map':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/map.mod/.bmx/map.bmx.debug.win32.x86.c:3361: undefined reference to `_bb_____brl_map_intmap'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/map.mod/.bmx/map.bmx.debug.win32.x86.c:3362: undefined reference to `_bb_____brl_map_ptrmap'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/map.mod/.bmx/map.bmx.debug.win32.x86.c:3363: undefined reference to `_bb_____brl_map_stringmap'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/map.mod/.bmx/map.bmx.debug.win32.x86.c:3364: undefined reference to `_bb_____brl_map_objectmap'
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/appstub.mod/appstub.debug.win32.x86.a(appstub.bmx.debug.win32.x86.o): In function `_bb_brl_appstub_appstub':
C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/mod/brl.mod/appstub.mod/.bmx/appstub.bmx.debug.win32.x86.c:7: undefined reference to `_bb_____brl_appstub_debugger_mt_stdio'
Build Error: Failed to link C:/Users/Dabz/Desktop/LAMB/BNGDumps/1448865038/BlitzMaxNG/tmp/untitled1.debug.exe
Process complete

Sorry about the wall of text, havent a clue how to format on here! :-D

Dabz

**Comment by GWRon** [comment]
Formatting is done via 
\`\`\`
your preformatted code
\`\`\`

If you use __\`\`\`BlitzMax__ it even highlights for BlitzMax (I pushed that change to the highlighter some months ago).


Try to recompile your modules after compiling the new BCC ... Bruce changed some things when munging code parts (adding/glueing with `___` for some things)

**Comment by Dabzy** [comment]
just realised, I setup MinGW (env var paths) for a bit of testing on another thing, I wonder if it's using that, instead of the one bundled with the official download?

Cannot test just yet, at the hens...

**Comment by woollybah** [comment]
The latest commit should fix that.

**Comment by woollybah** [comment]
Meh. "Top job" would have worked first time :-p
